////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  This file is part of NCrystal (see https://mctools.github.io/ncrystal/)   //
//                                                                            //
//  Copyright 2015-2026 NCrystal developers                                   //
//                                                                            //
//  Licensed under the Apache License, Version 2.0 (the "License");           //
//  you may not use this file except in compliance with the License.          //
//  You may obtain a copy of the License at                                   //
//                                                                            //
//      http://www.apache.org/licenses/LICENSE-2.0                            //
//                                                                            //
//  Unless required by applicable law or agreed to in writing, software       //
//  distributed under the License is distributed on an "AS IS" BASIS,         //
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  //
//  See the License for the specific language governing permissions and       //
//  limitations under the License.                                            //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include "NCrystal/internal/sgsym/NCSymOp.hh"

namespace NC = NCrystal;

namespace NCRYSTAL_NAMESPACE {
  namespace {

    using Mat = std::array<int,9>;//row-major integer 3x3 matrix

    Mat matMult( const Mat& a, const Mat& b )
    {
      Mat r;
      for ( int i = 0; i < 3; ++i )
        for ( int j = 0; j < 3; ++j )
          r[3*i+j] = a[3*i]*b[j] + a[3*i+1]*b[3+j] + a[3*i+2]*b[6+j];
      return r;
    }

    int matDet( const Mat& m )
    {
      return ( m[0] * ( m[4]*m[8] - m[5]*m[7] )
               - m[1] * ( m[3]*m[8] - m[5]*m[6] )
               + m[2] * ( m[3]*m[7] - m[4]*m[6] ) );
    }

    bool isSignedPermutation( const Mat& m )
    {
      //Exactly one non-zero entry (+-1) in each row and each column:
      for ( int i = 0; i < 3; ++i ) {
        int nrow = 0, ncol = 0;
        for ( int j = 0; j < 3; ++j ) {
          if ( m[3*i+j] )
            ++nrow;
          if ( m[3*j+i] )
            ++ncol;
        }
        if ( nrow != 1 || ncol != 1 )
          return false;
      }
      return true;
    }

    //The 24 rotations of point group 6/mmm in hexagonal axes, generated by
    //closure from a 6-fold rotation, a 2-fold rotation and the inversion:
    const std::vector<Mat>& hexagonalRotations()
    {
      static const std::vector<Mat> s_rots = []()
      {
        const Mat gens[3] = { { { 1,-1,0, 1,0,0, 0,0,1 } },//x-y,x,z
                              { { 0,1,0, 1,0,0, 0,0,-1 } },//y,x,-z
                              { { -1,0,0, 0,-1,0, 0,0,-1 } } };//-x,-y,-z
        std::vector<Mat> res{ Mat{ { 1,0,0, 0,1,0, 0,0,1 } } };
        for ( std::size_t i = 0; i < res.size(); ++i ) {
          for ( auto& g : gens ) {
            const Mat m = matMult( res[i], g );
            if ( std::find( res.begin(), res.end(), m ) == res.end() )
              res.push_back( m );
          }
        }
        nc_assert_always( res.size() == 24 );
        std::sort( res.begin(), res.end() );
        return res;
      }();
      return s_rots;
    }

    //Rotation type (ITA notation) from determinant and trace, or 0 if the
    //combination is not possible for a crystallographic rotation:
    int rotTypeFromDetTrace( int det, int trace )
    {
      if ( det == 1 ) {
        switch ( trace ) {
        case 3: return 1;
        case -1: return 2;
        case 0: return 3;
        case 1: return 4;
        case 2: return 6;
        default: return 0;
        }
      }
      nc_assert( det == -1 );
      switch ( trace ) {
      case -3: return -1;
      case 1: return -2;
      case 0: return -3;
      case -1: return -4;
      case -2: return -6;
      default: return 0;
      }
    }

    unsigned orderFromRotType( int rt )
    {
      switch ( rt ) {
      case 1: return 1;
      case 2: case -1: case -2: return 2;
      case 3: return 3;
      case 4: case -4: return 4;
      case 6: case -3: case -6: return 6;
      default: break;
      }
      nc_assert_always( false );
      return 0;
    }

    [[noreturn]] void throwBadStr( StrView s, const char * reason )
    {
      NCRYSTAL_THROW2(BadInput,"Invalid symmetry operation \""<<s<<"\": "
                      <<reason);
    }

    //Parse one component like "-x+y+1/2" (lower case, no spaces) into
    //coefficients of x, y, z and translation (in units of 1/24):
    void parseComponent( StrView full, StrView c, int* coefs, int& trans )
    {
      if ( c.empty() )
        throwBadStr( full, "empty component" );
      bool seen[3] = { false, false, false };
      trans = 0;
      std::size_t i = 0;
      const std::size_t n = c.size();
      bool first = true;
      while ( i < n ) {
        int sign = 1;
        if ( c[i] == '+' || c[i] == '-' ) {
          sign = ( c[i] == '-' ? -1 : 1 );
          ++i;
        } else if ( !first ) {
          throwBadStr( full, "missing sign between terms" );
        }
        first = false;
        if ( i >= n )
          throwBadStr( full, "incomplete term" );
        const char ch = c[i];
        if ( ch == 'x' || ch == 'y' || ch == 'z' ) {
          const int idx = ch - 'x';
          if ( seen[idx] )
            throwBadStr( full, "repeated variable within component" );
          seen[idx] = true;
          coefs[idx] = sign;
          ++i;
          continue;
        }
        if ( !( ch >= '0' && ch <= '9' ) ) {
          if ( ch == '.' )
            throwBadStr( full, "decimal translations are not supported"
                         " (use fractions like 1/2)" );
          throwBadStr( full, "unexpected character" );
        }
        //Integer or fraction:
        auto readUInt = [&full,&c,&i,n]()
        {
          std::int64_t v = 0;
          unsigned ndigits = 0;
          while ( i < n && c[i] >= '0' && c[i] <= '9' ) {
            if ( ++ndigits > 9 )
              throwBadStr( full, "number too long" );
            v = 10 * v + ( c[i] - '0' );
            ++i;
          }
          return v;
        };
        const std::int64_t num = readUInt();
        std::int64_t den = 1;
        if ( i < n && c[i] == '/' ) {
          ++i;
          if ( !( i < n && c[i] >= '0' && c[i] <= '9' ) )
            throwBadStr( full, "invalid fraction" );
          den = readUInt();
          if ( den == 0 )
            throwBadStr( full, "division by zero" );
        }
        if ( i < n && ( c[i] == '.' ) )
          throwBadStr( full, "decimal translations are not supported"
                       " (use fractions like 1/2)" );
        if ( i < n && ( c[i] == 'x' || c[i] == 'y' || c[i] == 'z' ) )
          throwBadStr( full, "coefficients of x, y, z must be +1 or -1" );
        if ( ( num * SymOp::tdenom ) % den != 0 )
          throwBadStr( full, "translations must be multiples of 1/24" );
        //(reduced modulo 1, i.e. 24, to avoid overflows):
        trans += sign * static_cast<int>( ( num * SymOp::tdenom / den )
                                          % SymOp::tdenom );
      }
    }
  }
}

NC::SymOp::SymOp( const std::array<int,9>& rot,
                  const std::array<int,3>& trans )
{
  for ( auto v : rot )
    if ( !( v >= -1 && v <= 1 ) )
      NCRYSTAL_THROW(BadInput,"Symmetry operations must have rotation"
                     " matrix entries in {-1,0,1}");
  if ( !isAllowedRotation( rot ) )
    NCRYSTAL_THROW(BadInput,"Symmetry operations must have a rotation part"
                   " belonging to point group m-3m with orthogonal-type axes"
                   " (i.e. a signed permutation matrix) or point group"
                   " 6/mmm with hexagonal axes");
  for ( auto i : ncrange( 9 ) )
    m_data[i] = static_cast<std::int8_t>( rot[i] );
  for ( auto i : ncrange( 3 ) )
    m_data[9+i] = reduceTrans( trans[i] % tdenom );
}

NC::SymOp::SymOp( StrView s )
{
  //Normalise (remove whitespace, lower case):
  std::string norm;
  norm.reserve( s.size() );
  for ( char ch : s ) {
    if ( ch == ' ' || ch == '\t' )
      continue;
    if ( ch >= 'A' && ch <= 'Z' )
      ch = static_cast<char>( ch - 'A' + 'a' );
    norm += ch;
  }
  const StrView sv( norm );
  const auto parts = sv.split<3>( ',' );
  if ( parts.size() != 3 )
    throwBadStr( s, "expected three comma-separated components" );
  std::array<int,9> rot;
  std::array<int,3> trans;
  rot.fill( 0 );
  for ( auto i : ncrange( 3 ) )
    parseComponent( s, parts.at( i ), &rot[3*i], trans[i] );
  try {
    *this = SymOp( rot, trans );
  } catch ( Error::BadInput& e ) {
    throwBadStr( s, e.what() );
  }
}

bool NC::SymOp::isAllowedRotation( const std::array<int,9>& m ) noexcept
{
  for ( auto v : m )
    if ( !( v >= -1 && v <= 1 ) )
      return false;
  if ( isSignedPermutation( m ) )
    return true;
  const auto& h = hexagonalRotations();
  return std::binary_search( h.begin(), h.end(), m );
}

void NC::SymOp::throwInvalidProduct( const SymOp& a, const SymOp& b )
{
  NCRYSTAL_THROW2(LogicError,"Invalid composition of symmetry operations "
                  <<a<<" and "<<b<<" (they can not belong to the same space"
                  " group, since one of their rotation parts refers to"
                  " hexagonal axes and the other to orthogonal-type axes)");
}

bool NC::SymOp::isIdentity() const noexcept
{
  return *this == SymOp();
}

bool NC::SymOp::hasTranslation() const noexcept
{
  return m_data[9] || m_data[10] || m_data[11];
}

int NC::SymOp::determinant() const noexcept
{
  Mat m;
  for ( auto i : ncrange( 9 ) )
    m[i] = m_data[i];
  return matDet( m );
}

int NC::SymOp::rotationType() const noexcept
{
  const int rt = rotTypeFromDetTrace( determinant(),
                                      m_data[0] + m_data[4] + m_data[8] );
  nc_assert( rt != 0 );
  return rt;
}

unsigned NC::SymOp::rotationOrder() const noexcept
{
  return orderFromRotType( rotationType() );
}

NC::SymOp NC::SymOp::inverse() const noexcept
{
  //R^-1 = adj(R)/det(R), and t' = -R^-1 t:
  const auto& d = m_data;
  const int det = determinant();
  const Mat adj = { { d[4]*d[8]-d[5]*d[7], d[2]*d[7]-d[1]*d[8],
                      d[1]*d[5]-d[2]*d[4],
                      d[5]*d[6]-d[3]*d[8], d[0]*d[8]-d[2]*d[6],
                      d[2]*d[3]-d[0]*d[5],
                      d[3]*d[7]-d[4]*d[6], d[1]*d[6]-d[0]*d[7],
                      d[0]*d[4]-d[1]*d[3] } };
  std::array<std::int8_t,12> r;
  for ( auto i : ncrange( 9 ) ) {
    const int v = adj[i] * det;
    nc_assert( v >= -1 && v <= 1 );
    r[i] = static_cast<std::int8_t>( v );
  }
  for ( int i = 0; i < 3; ++i )
    r[9+i] = reduceTrans( -( r[3*i] * d[9] + r[3*i+1] * d[10]
                             + r[3*i+2] * d[11] ) );
  return SymOp( NoCheck(), r );
}

std::string NC::SymOp::toString() const
{
  std::string res;
  for ( int i = 0; i < 3; ++i ) {
    if ( i )
      res += ',';
    bool first = true;
    for ( int j = 0; j < 3; ++j ) {
      const int c = m_data[3*i+j];
      if ( !c )
        continue;
      if ( c < 0 )
        res += '-';
      else if ( !first )
        res += '+';
      res += static_cast<char>( 'x' + j );
      first = false;
    }
    nc_assert( !first );//det!=0 implies non-zero rows
    const int t = m_data[9+i];
    if ( t ) {
      int g = tdenom;//gcd(t,tdenom):
      for ( int a = t; a; ) {
        const int tmp = g % a;
        g = a;
        a = tmp;
      }
      res += '+';
      res += std::to_string( t / g );
      res += '/';
      res += std::to_string( tdenom / g );
    }
  }
  return res;
}

std::ostream& NC::operator<<( std::ostream& os, const SymOp& op )
{
  return os << op.toString();
}
