name: ncrystal_devel
channels:
  - nodefaults
  - conda-forge
dependencies:
  - c-compiler
  - cmake
  - cxx-compiler
  - make
  - pip
  - python
  - ase >=3.23.0
  - cppcheck
  - endf-parserpy <=0.13.99
  - gemmi >=0.6.1
  - matplotlib >=3.6.0
  - mpmath >=1.3.0
  - numpy >=1.22
  - pybind11 >=2.11.0
  - PyYAML >=6.0.0
  - ruff >=0.8.1
  - simple-build-system >=1.6.0
  - spglib >=2.1.0
  - tomli >=2.0.0
