#!/bin/bash

################################################################################
##                                                                            ##
##  This file is part of NCrystal (see https://mctools.github.io/ncrystal/)   ##
##                                                                            ##
##  Copyright 2015-2017 NCrystal developers                                   ##
##                                                                            ##
##  Licensed under the Apache License, Version 2.0 (the "License");           ##
##  you may not use this file except in compliance with the License.          ##
##  You may obtain a copy of the License at                                   ##
##                                                                            ##
##      http://www.apache.org/licenses/LICENSE-2.0                            ##
##                                                                            ##
##  Unless required by applicable law or agreed to in writing, software       ##
##  distributed under the License is distributed on an "AS IS" BASIS,         ##
##  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  ##
##  See the License for the specific language governing permissions and       ##
##  limitations under the License.                                            ##
##                                                                            ##
################################################################################

set -e
set -u

if [ -f ./NCrystalLink -o -d ./NCrystalLink ]; then
    echo "Found ./NCrystalLink already (remove and rerun to force reinstallation)"
    exit 1
fi
nccompfn="NCrystal_sample.comp"
if [ -f ./$nccompfn ]; then
    echo "Found ./$nccompfn (remove and rerun to force reinstallation)"
    exit 1
fi


THISDIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
if [ "${NCRYSTALDIR+x}" == "x" -a -f "$THISDIR"/../mcstas/NCrystal_sample.comp ]; then
    ln -s "$NCRYSTALDIR" ./NCrystalLink
    ln -s "$THISDIR"/../mcstas/NCrystal_sample.comp .
fi
