#!/usr/bin/env python3

################################################################################
##                                                                            ##
##  This file is part of NCrystal (see https://mctools.github.io/ncrystal/)   ##
##                                                                            ##
##  Copyright 2015-2025 NCrystal developers                                   ##
##                                                                            ##
##  Licensed under the Apache License, Version 2.0 (the "License");           ##
##  you may not use this file except in compliance with the License.          ##
##  You may obtain a copy of the License at                                   ##
##                                                                            ##
##      http://www.apache.org/licenses/LICENSE-2.0                            ##
##                                                                            ##
##  Unless required by applicable law or agreed to in writing, software       ##
##  distributed under the License is distributed on an "AS IS" BASIS,         ##
##  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  ##
##  See the License for the specific language governing permissions and       ##
##  limitations under the License.                                            ##
##                                                                            ##
################################################################################

import matplotlib.pyplot as plt
import numpy as np
import NCrystalDev as NC
try:
    import NCrystal as NCenv
    if not any(name=='CrysExtn' for name,_,_ in NCenv.browsePlugins()):
        NCenv = None
except ImportError:
    NCenv = None
if not NCenv:
    raise SystemExit('This script needs the CrysExtn plugin'
                     ' available in the environent')

def create_data( base, custom = None ):
    key = base if base.startswith('stdlib::') else f'stdlib::{base}'
    #Always taking base material from NCrystalDev for consistency:
    td = NC.createTextData(key)
    return ( f'{td.rawData}\n@CUSTOM_CRYSEXTN\n{custom}'
             if custom else str(td.rawData) )

def load( ncmod, ncmatdata, cfg_params ):
    return ncmod.directLoad(ncmatdata,
                            dtype='ncmat',
                            cfg_params=cfg_params,
                            doAbsorption=False)

base = 'stdlib::Be_sg194.ncmat'
common = 'dcutoff=1.5;comp=bragg'

mat_dev = load(NC,create_data(base),common)
mat_ref = load(NCenv,create_data(base,
                                 custom='BC_pure  0  1000  100000  Gauss'),
               common)

wls = np.linspace(0.5,6.0,1000)
plt.plot(wls,mat_dev.xsect(wl=wls),label='devel')
plt.plot(wls,mat_ref.xsect(wl=wls),label='ref')
plt.show()
