#!/usr/bin/env python3

################################################################################
##                                                                            ##
##  This file is part of NCrystal (see https://mctools.github.io/ncrystal/)   ##
##                                                                            ##
##  Copyright 2015-2026 NCrystal developers                                   ##
##                                                                            ##
##  Licensed under the Apache License, Version 2.0 (the "License");           ##
##  you may not use this file except in compliance with the License.          ##
##  You may obtain a copy of the License at                                   ##
##                                                                            ##
##      http://www.apache.org/licenses/LICENSE-2.0                            ##
##                                                                            ##
##  Unless required by applicable law or agreed to in writing, software       ##
##  distributed under the License is distributed on an "AS IS" BASIS,         ##
##  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  ##
##  See the License for the specific language governing permissions and       ##
##  limitations under the License.                                            ##
##                                                                            ##
################################################################################

_wikitarget='CfgRefDoc.md'
_wikicfgstrlinktarget='Using-NCrystal.md'

def gen_wiki_cfgvarrefdoc():
    import NCrystalDev as NC
    ncversion=NC.__version__
    ll=['# NCrystal cfg-parameters reference documentation',
       '<!-- WARNING: PAGE AUTOMATICALLY GENERATED DO NOT EDIT DIRECTLY -->',
       ('Reference documentation of all [[cfg-string '
       '|%s]] variables, generated with NCrystal release v%s.')
       %(_wikicfgstrlinktarget.split('.')[0],ncversion),
       '']
    data = NC.generateCfgStrDoc('python')
    for group in data:
        ll.append('')
        ll.append('## %s'%group['group_description'])
        for p in group['parameters']:
            ll.append('<details>')
            title=p['name']
            if p['type']=='pseudo':
                title+=' (pseudo parameter)'
            ll.append('  <summary>%s</summary>'%title)
            ll.append('')#important with empty line here!
            ll.append('> **Type:** %s  '%p['type'])#Note that 2 trailing spaces
                                                   #indicates new line
            au=p.get('allowed_input_units',None)
            if au is not None:
                ll.append('> **Allowed input units:** %s  '%au)
            defval=p.get('default_value_str',None)
            if defval is not None:
                if p['type']=='string':
                    defval=f'"{defval}"'
                ll.append('> **Default value:** %s  '%defval)
            ll.append('> **Description:** %s  '%p['description'].strip())
            ll.append('')
            ll.append('</details>')
            ll.append('')#important with empty line here!

    return ncversion,ll

if __name__=='__main__':
    import pathlib
    import sys
    args=sys.argv[1:]
    if not len(args)==1:
        raise SystemExit('Please provide path to ncrystal.wiki repo')
    ncwikirepo = pathlib.Path(args[0]).absolute().resolve()
    if not ncwikirepo.exists() or not ncwikirepo.is_dir():
        raise SystemExit(f'Not a diretory: {ncwikirepo}')

    for f in ('.git',_wikitarget,_wikicfgstrlinktarget):
        _ = ncwikirepo / f
        if not _.exists():
            raise SystemExit(f'{ncwikirepo} does not seem to be correct'
                             f' (missing expected file: {f})')
    print(f'Querying NCrystal to generate new contents for {_wikitarget}')
    ncversion,newfilecontent = gen_wiki_cfgvarrefdoc()
    newfilecontent = '\n'.join(newfilecontent)
    ftarget = ncwikirepo / _wikitarget
    assert ftarget.exists()
    old_content = ftarget.read_text()
    if old_content == newfilecontent:
        print("File content does not change - nothing to do.")
        raise SystemExit
    else:
        for i in range(999999):
            b = ftarget.parent.joinpath(ftarget.name+'_OLD')
            if not b.is_file():
                break
        b.write_text(old_content)
        print(f"Saved backup of old content: {b}")
    ftarget.write_text(newfilecontent)
    print(f'Updated {ftarget}\n')
