#!/usr/bin/env python3

################################################################################
##                                                                            ##
##  This file is part of NCrystal (see https://mctools.github.io/ncrystal/)   ##
##                                                                            ##
##  Copyright 2015-2026 NCrystal developers                                   ##
##                                                                            ##
##  Licensed under the Apache License, Version 2.0 (the "License");           ##
##  you may not use this file except in compliance with the License.          ##
##  You may obtain a copy of the License at                                   ##
##                                                                            ##
##      http://www.apache.org/licenses/LICENSE-2.0                            ##
##                                                                            ##
##  Unless required by applicable law or agreed to in writing, software       ##
##  distributed under the License is distributed on an "AS IS" BASIS,         ##
##  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  ##
##  See the License for the specific language governing permissions and       ##
##  limitations under the License.                                            ##
##                                                                            ##
################################################################################

# Small script which loads the JSON data generated from the sibling
# mmcscalingplot script, and produces plots of MiniMC timing versus number of
# threads, fits Amdahl's law, etc.

def fit_amdahl( nthreads, throughput, throughput_stddev ):
    #normalise so first throughput is 1:
    import numpy as np
    x = np.asarray(nthreads[:])
    y = np.asarray(throughput[:])
    y_stddev = np.asarray(throughput_stddev[:])
    yscale = y[0]
    y /= yscale
    y_stddev /= yscale
    def fit_func( x, f ):
        return 1.0 / ( ( 1.0 - f ) + f / x )
    from scipy.optimize import curve_fit

    res_params, res_param_err = curve_fit(fit_func,x,y,sigma=y_stddev)
    print("Fitted f=%g"%res_params[0])

    xx = np.linspace(x[0],x[-1],1000)
    return xx, yscale * fit_func(xx,res_params[0]),res_params[0]

def prettyfmt(x):
    from NCrystalDev._common import _frexp10
    b,e = _frexp10(x)
    if b==1 and e>3:
        return f'1e{e}'
    return repr(x)

def _res2title(results):
    n = [ nvals for nvals, nthreads2times in results['results'].items() ]
    sc = results['src_cfg']
    if len(set(n))==1 and ';n=' not in (';'+sc):
        sc += ';n=%s'%prettyfmt(int(n[0]))
    return'"%s", src="%s", geom="%s"'%(results['mat_cfgstr'],
                                       sc,
                                       results['geom_cfgstr'])

def plot_results(results, use_seen_rates = True):
    import matplotlib.pyplot as plt
    import numpy as np
    max_rate = 0.0

    #overhead = results['overhead']
    overhead = 0.0#ignore, not reliable with threading
    for nvals, nthreads2times in sorted(results['results'].items()):
        vals_nthread = []
        vals_ratemin = []
        vals_ratemax = []
        vals_stddev = []
        vals_rate = []
        label = f'n={float(nvals):g}'
        rate_thread1 = None
        for nthread,raw_times_and_nseen in sorted((int(n),d) for n,d in nthreads2times.items()):
            vals_nthread.append( nthread )
            if use_seen_rates:
                _rates_mhz = [ ( nseen*1e-6 / (t-overhead))  for t,nseen,tini in raw_times_and_nseen ]
            else:
                _rates_mhz = [ ( float(nvals)*1e-6 / (t-overhead))  for t,nseen,tini in raw_times_and_nseen ]
            vals_ratemin.append( min(_rates_mhz) )
            vals_ratemax.append( max(_rates_mhz) )
            vals_stddev.append( np.std(_rates_mhz) )
            #vals_rate.append( sum(_rates_mhz)/len(_rates_mhz) )
            #vals_rate.append( np.median(_rates_mhz) )
            vals_rate.append( np.mean(_rates_mhz) )
            #vals_rate.append( max(_rates_mhz) )
            if nthread==1 and rate_thread1 is None:
                rate_thread1 = (vals_ratemax[-1],vals_ratemin[-1],vals_rate[-1])
        _=plt.plot(vals_nthread, vals_rate, '-', label = label)
        color=_[0].get_color()
        plt.fill_between(vals_nthread, vals_ratemin, vals_ratemax, color=color,alpha=0.2)
        max_rate = max(max_rate,max(vals_ratemax))

        if rate_thread1 is not None:
            for i in range(3):
                plt.plot( [ 0.0, vals_nthread[-1] ],
                          [ 0.0, vals_nthread[-1] * rate_thread1[i] ],
                          color = color, ls = ':', alpha = 0.5 )

    xa,ya,fa = fit_amdahl(vals_nthread[:],vals_rate[:],vals_stddev[:])
    plt.plot(xa,ya,label='Amdahl (p=%g)'%fa)

    plt.legend()
    #plt.title('src="%s", job overhead: %g seconds'%(results['src_cfg'],overhead))

    plt.title(_res2title(results))
    plt.ylim(0.0,1.2*max_rate )
    if use_seen_rates:
        plt.ylabel('MHz (tallied particles)')
    else:
        plt.ylabel('MHz (source particles)')
    plt.xlabel('Number of threads')
    plt.grid()
    plt.show()

def plot_results_jobtime(results):
    import matplotlib.pyplot as plt
    #max_rate = 0.0

    overhead = results['overhead']
    overhead = 0.0#ignore??
    #overhead = 0.0#ignore, not reliable with threading
    for nvals, nthreads2times in sorted(results['results'].items()):
        vals_nthread = []
        vals_tmin = []
        vals_tmax = []
        vals_tinimin = []
        vals_tinimax = []
        vals_t = []
        vals_tini = []
        #label = f'n={float(nvals):g}'
        for nthread,raw_times_and_nseen in sorted((int(n),d) for n,d in nthreads2times.items()):
            vals_nthread.append( nthread )
            tvals = [ t  for t,nseen,tini in raw_times_and_nseen ]
            tinivals = [ tini  for t,nseen,tini in raw_times_and_nseen ]
            vals_tmin.append( min(tvals) )
            vals_tmax.append( max(tvals) )
            vals_tinimin.append( min(tinivals) )
            vals_tinimax.append( max(tinivals) )
            vals_t.append( sum(tvals)/len(tvals) )
            vals_tini.append( sum(tinivals)/len(tinivals) )
        _t=plt.plot(vals_nthread, vals_t, '-', label = 'MiniMC simulation')
        _tini=plt.plot(vals_nthread, vals_tini, '-', color='tab:orange',label = 'Material initialisation')
        color=_t[0].get_color()
        plt.fill_between(vals_nthread, vals_tmin, vals_tmax, color=color,alpha=0.2)
        color=_tini[0].get_color()
        plt.fill_between(vals_nthread, vals_tinimin, vals_tinimax, color=color,alpha=0.2)

    if overhead:
        obj = plt.fill_between( [ 1.0, vals_nthread[-1] ],
                                [0.0,0.0],
                                [ overhead, overhead ],
                                color = 'tab:orange', ls = ':',
                                alpha=0.3,
                                label='Other overhead' )

        obj.set_hatch("///")        # apply hatch
        #obj.set_edgecolor("black")  # hatch uses edge color
        obj.set_linewidth(0.5)      # hatch line width

#        plt.plot( [ 0.0, vals_nthread[-1] ],
#                  [ overhead, overhead ],
#                  color = 'red', ls = ':',
#                  label='material initialisation' )
#                  #alpha = 0.5 )

    plt.legend()
    #plt.title('src="%s", job overhead: %g seconds'%(results['src_cfg'],overhead))
    plt.title(_res2title(results))
    #plt.title('src="%s"'%results['src_cfg'])
    plt.ylim(0.0)
    plt.ylabel('Job time (seconds)')
    plt.xlabel('Number of threads')
    plt.grid()
    plt.show()

if __name__=='__main__':
    import json
    import pathlib
    import os
    import sys
    data = json.loads(pathlib.Path(os.path.expanduser(sys.argv[1])).read_text())
    plot_results(data,use_seen_rates=True)
    plot_results(data,use_seen_rates=False)
    plot_results_jobtime(data)
