name: basictest_wincmake

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: src

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: CMake cfg NCrystal
      shell: cmd
      run: cmake -B build src -DNCRYSTAL_ENABLE_TESTING=ON -DNCRYSTAL_ENABLE_EXAMPLES=ON

    - name: Look around
      shell: cmd
      run: |
        tree build

    - name: CMake build NCrystal
      shell: cmd
      run: cmake --build build --config Release  -- /verbosity:detailed

#cmake --build . --target INSTALL -- /verbosity:detailed
    - name: Run CTests
      shell: cmd
      run: |
        cd build
        ctest

    - name: CMake install NCrystal
      shell: cmd
      run: cmake --build build --target INSTALL --config Release  -- /verbosity:detailed
