name: mingw

on:
  push:
  pull_request:

jobs:
#  ncdevtool_check:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#        with:
#          path: src
#      - name: Pip install packages for ncdevtool
#        run: pip install -r ./src/devel/reqs/requirements_devel.txt
#      - name: ncdevtool checks
#        run: ./src/devel/bin/ncdevtool check -n "fix""me"
#

  build:
#    needs: [ ncdevtool_check ]
    strategy:
      matrix:
        #os: [windows-2019, windows-2022]
        os: [windows-2022]
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    #windows-latest is windows-2022 (Nov 2024)

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: msys2/setup-msys2@v2

    - name: Checkout
      uses: actions/checkout@v4
      with:
        path: src

    - name: Enable parallel cmake
      run: python ./src/devel/bin/ncdevtool nprocs --enable-github-parallel

    - name: Monolithic pip install of repo
      env:
        CC: gcc
        CXX: g++
      run: python -m pip install -v  ./src

    - name: ncrystal-config summary
      run: ncrystal-config --summary

#    - name: Setup python
#      uses: actions/setup-python@v5
#      with:
#        python-version: 3.11
#
