name: pypi

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  preparations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: src
          fetch-tags: true

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Pip install packages for ncdevtool
        run: pip install -r ./src/devel/reqs/requirements_devel.txt

      - name: ncdevtool checks
        run: ./src/devel/bin/ncdevtool check -n "fix""me"

      - name: Verify version number
        id: version-number
        run: |
          set -eux
          VERSIONSTR=$(./src/devel/bin/ncdevtool verifytag --fail-if-devel -p 'vX.Y.Z' --file-verify=VERSION)
          echo "Extracted version str: '${VERSIONSTR}'"
          echo "version_number=$VERSIONSTR" >> $GITHUB_OUTPUT

    outputs:
      ncrystalversion: ${{ steps.version-number.outputs.version_number }}

  basic_functionality_test:
    #Very basic testing only, we might have decided to publish a release even
    #with some tests showing spurious failures or similar. However, we always
    #tell users that "nctool --test" can be used to test that everything works,
    #so at least that should always work.
    needs: [ preparations ]
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-13, macos-14]
        #        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        #NOTICE: Keep synchronised with matrix platform list elsewhere in this file!!!!
    name: ${{ matrix.os }} / test
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: src

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Enable parallel cmake
        run: python ./src/devel/bin/ncdevtool nprocs --enable-github-parallel

      - name: Pip install ncrystal-core
        run: pip install ./src/ncrystal_core

      - name: Pip install ncrystal-python
        run: pip install ./src/ncrystal_python

      - name: Pip install ncrystal
        run: pip install ./src/ncrystal_metapkg

      - name: Pip install ncrystal-verify
        run: pip install ./src/ncrystal_verify

      - name: nctool tests
        run: nctool --test

      - name: cmdline presence tests
        run: python -m "NCrystal.test" cmdline

      - name: Pip install extra deps
        run: pip install -r ./src/devel/reqs/requirements_all_and_devel.txt

      - name: ncrystal-verify
        run: ncrystal-verify

  build_sdists:
    name: Build source distribution
    runs-on: ubuntu-latest
    needs: preparations
    env:
      SDIST_SUFFIX: "-${{ needs.preparations.outputs.ncrystalversion }}.tar.gz"

    steps:
      - uses: actions/checkout@v4

      - name: build ncrystal-core sdist
        run: pipx run build --sdist ./ncrystal_core

      - name: build ncrystal-python sdist
        run: pipx run build --sdist ./ncrystal_python

      - name: build ncrystal-metapkg sdist
        run: pipx run build --sdist ./ncrystal_metapkg

      - name: build ncrystal-verify sdist
        run: pipx run build --sdist ./ncrystal_verify

      - name: register ncrystal-core sdist
        uses: actions/upload-artifact@v4
        with:
          name: sdist-ncrystal-core
          path: ./ncrystal_core/dist/ncrystal_core${{ env.SDIST_SUFFIX }}
          if-no-files-found: error

      - name: register ncrystal-python sdist
        uses: actions/upload-artifact@v4
        with:
          name: sdist-ncrystal-python
          path: ./ncrystal_python/dist/ncrystal_python${{ env.SDIST_SUFFIX }}
          if-no-files-found: error

      - name: register ncrystal-metapkg sdist
        uses: actions/upload-artifact@v4
        with:
          name: sdist-ncrystal-metapkg
          path: ./ncrystal_metapkg/dist/ncrystal${{ env.SDIST_SUFFIX }}
          if-no-files-found: error

      - name: register ncrystal-verify sdist
        uses: actions/upload-artifact@v4
        with:
          name: sdist-ncrystal-verify
          path: ./ncrystal_verify/dist/ncrystal_verify${{ env.SDIST_SUFFIX }}
          if-no-files-found: error

    outputs:
      sdistname_core: ncrystal_core${{ env.SDIST_SUFFIX }}
      sdistname_python: ncrystal_python${{ env.SDIST_SUFFIX }}
      sdistname_metapkg: ncrystal${{ env.SDIST_SUFFIX }}
      sdistname_verify: ncrystal_verify${{ env.SDIST_SUFFIX }}

  build_pure_wheels:
    name: Build pure wheels
    runs-on: ubuntu-latest
    needs: [ preparations, build_sdists ]

    steps:
      - name: download ncrystal-python sdist
        uses: actions/download-artifact@v4
        with:
          name: sdist-ncrystal-python
          path: ./sdist-python

      - name: download ncrystal-metapkg sdist
        uses: actions/download-artifact@v4
        with:
          name: sdist-ncrystal-metapkg
          path: ./sdist-metapkg

      - name: download ncrystal-verify sdist
        uses: actions/download-artifact@v4
        with:
          name: sdist-ncrystal-verify
          path: ./sdist-verify

      - name: build ncrystal-python pure wheel
        run: |
          set -eux
          mkdir tmp_wheelbld_python
          cd tmp_wheelbld_python
          tar xf ../sdist-python/${{needs.build_sdists.outputs.sdistname_python }}
          pipx run build --wheel ./ncrystal_python-${{ needs.preparations.outputs.ncrystalversion }} --outdir=../dist-ncrystal-python

      - name: build ncrystal-metapkg pure wheel
        run: |
          set -eux
          mkdir tmp_wheelbld_metapkg
          cd tmp_wheelbld_metapkg
          tar xf ../sdist-metapkg/${{needs.build_sdists.outputs.sdistname_metapkg }}
          pipx run build --wheel ./ncrystal-${{ needs.preparations.outputs.ncrystalversion }} --outdir=../dist-ncrystal-metapkg

      - name: build ncrystal-verify pure wheel
        run: |
          set -eux
          mkdir tmp_wheelbld_verify
          cd tmp_wheelbld_verify
          tar xf ../sdist-verify/${{needs.build_sdists.outputs.sdistname_verify }}
          pipx run build --wheel ./ncrystal_verify-${{ needs.preparations.outputs.ncrystalversion }} --outdir=../dist-ncrystal-verify

      - name: register ncrystal-python pure wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheel-ncrystal-python
          path: ./dist-ncrystal-python/ncrystal_python-${{ needs.preparations.outputs.ncrystalversion }}-py3-none-any.whl
          if-no-files-found: error

      - name: register ncrystal-metapkg pure wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheel-ncrystal-metapkg
          path: ./dist-ncrystal-metapkg/ncrystal-${{ needs.preparations.outputs.ncrystalversion }}-py3-none-any.whl
          if-no-files-found: error

      - name: register ncrystal-verify pure wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheel-ncrystal-verify
          path: ./dist-ncrystal-verify/ncrystal_verify-${{ needs.preparations.outputs.ncrystalversion }}-py3-none-any.whl
          if-no-files-found: error

  build_core_wheels:
    #Based on
    #https://github.com/pypa/cibuildwheel/blob/main/examples/github-minimal.yml,
    #where we should check if something needs updating once in a while
    #(especially with respect to the hardcoded matrix.os list.
    needs: [ preparations, build_sdists ]
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-13, macos-14]
        #        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        #NOTICE: Keep synchronised with matrix platform list elsewhere in this file!!!!
    name: ${{ matrix.os }} / ncrystal-core wheels
    runs-on: ${{ matrix.os }}

    env:
      SDIST_PATH: "./sdist/${{ needs.build_sdists.outputs.sdistname_core }}"

    steps:
      - name: download ncrystal-core sdist
        uses: actions/download-artifact@v4
        with:
          name: sdist-ncrystal-core
          path: ./sdist

      - name: Look in sdist dir (unix)
        if: runner.os != 'Windows'
        run: ls -l "${SDIST_PATH}"

      - name: Verify presence of sdist (unix)
        if: runner.os != 'Windows'
        run: test -f "${SDIST_PATH}"

      # Run cibuildwheel. Both in default mode, and with additional steps for
      # manylinux_2_28 wheels, with more modern C++ support (and in particular
      # cxxabi std::string's compatible with modern linux installations):
      #
      # Note from cibuildwheel docs: "The default is scheduled to change in a
      # cibuildwheel release on or after 6th May 2025 - if you don't want the
      # new default, you should set the value to manylinux2014." So when that
      # happens, we can remove the 2_28 step, or possibly swap it for 2_34 and
      # manylinux2014:
      #
      # Additionally, also try to make windows-arm64 wheels through cross
      # compilation.

      - name: cibuildwheel
        uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_ARCHS_WINDOWS: "auto ARM64"
        with:
          package-dir: ${{ env.SDIST_PATH }}
          output-dir: wheelhouse

      - name: cibuildwheel manylinux_2_28
        uses: pypa/cibuildwheel@v2.22.0
        if: runner.os == 'Linux'
        env:
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          CIBW_MANYLINUX_AARCH64_IMAGE: manylinux_2_28
        with:
          package-dir: ${{ env.SDIST_PATH }}
          output-dir: wheelhouse

      - name: list wheelhouse (unix)
        if: runner.os != 'Windows'
        run: ls -l ./wheelhouse/

      - name: list wheelhouse (windows)
        if: runner.os == 'Windows'
        run: dir wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: ncrystal-core-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/ncrystal_core-*.whl
          if-no-files-found: error

  collect_output:
    name: Collect all output
    needs: [preparations, build_sdists, build_core_wheels, build_pure_wheels]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: "ncrystal-core-wheels-*"
          path: ncrystal-core-wheels-raw #unpacks all artifacts into ncrystal-core-wheels-raw/
          #Todo if we use merge-multiple: 'true', we might not have to do the
          #find trick below

      - name: Look in ncrystal-core-wheels-raw
        run: find ./ncrystal-core-wheels-raw/

        #gh-action-pypi-publish expects a flat directory layout
      - name: Move core wheel files into dist_core
        run: |
            mkdir -p dist_core
            find ./ncrystal-core-wheels-raw/ -type f -name "ncrystal_core-*.whl" -exec mv {} dist_core/ \;

      - name: list collected files
        run: ls -l ./dist_core

      - name: download ncrystal-core sdist
        uses: actions/download-artifact@v4
        with:
          name: sdist-ncrystal-core
          path: ./dist_core

      - name: download ncrystal-python pure wheel
        uses: actions/download-artifact@v4
        with:
          name: wheel-ncrystal-python
          path: ./dist_python

      - name: download ncrystal-metapkg pure wheel
        uses: actions/download-artifact@v4
        with:
          name: wheel-ncrystal-metapkg
          path: ./dist_metapkg

      - name: download ncrystal-verify pure wheel
        uses: actions/download-artifact@v4
        with:
          name: wheel-ncrystal-verify
          path: ./dist_verify

      - name: download ncrystal-python sdist
        uses: actions/download-artifact@v4
        with:
          name: sdist-ncrystal-python
          path: ./dist_python

      - name: download ncrystal-metapkg sdist
        uses: actions/download-artifact@v4
        with:
          name: sdist-ncrystal-metapkg
          path: ./dist_metapkg

      - name: download ncrystal-verify sdist
        uses: actions/download-artifact@v4
        with:
          name: sdist-ncrystal-verify
          path: ./dist_verify

      - name: List files
        run: |
          find ./dist_core
          find ./dist_python
          find ./dist_metapkg
          find ./dist_verify

      - name: Verify presence of expected ncrystal-core files
        shell: python
        run: |
          import pathlib
          pdir = pathlib.Path('./dist_core').absolute()
          expected_keys = [
            "macosx_10_9_x86_64",
            "macosx_11_0_arm64",
            "manylinux_2_17_i686.manylinux2014_i686",
            "manylinux_2_17_x86_64.manylinux2014_x86_64",
            "manylinux_2_27_x86_64.manylinux_2_28_x86_64",
            "manylinux_2_17_aarch64.manylinux2014_aarch64",
            "manylinux_2_27_aarch64.manylinux_2_28_aarch64",
            "musllinux_1_2_i686",
            "musllinux_1_2_x86_64",
            "musllinux_1_2_aarch64",
            "win32",
            "win_amd64",
            "win_arm64",
          ]
          versionstr = '${{ needs.preparations.outputs.ncrystalversion }}'
          prefix = f'ncrystal_core-{versionstr}-py3-none-'
          expected_files = set([ f'{prefix}{key}.whl' for key in expected_keys ])
          expected_files.add(f'ncrystal_core-{versionstr}.tar.gz')
          actual_files = set(f.name for f in pdir.iterdir())
          if expected_files - actual_files:
            raise SystemExit('Missing files: %s'%sorted(expected_files - actual_files))
          if actual_files - expected_files :
            raise SystemExit('Unexpected files: %s'%sorted(actual_files - expected_files))
          print("Found exactly the expected files:")
          for f in sorted(expected_files):
            print(f'  {f}')

      - name: Verify presence of expected ncrystal-python files
        run: |
          set -eux
          test -f ./dist_python/ncrystal_python-${{ needs.preparations.outputs.ncrystalversion }}.tar.gz
          test -f ./dist_python/ncrystal_python-${{ needs.preparations.outputs.ncrystalversion }}-py3-none-any.whl

      - name: Verify presence of expected ncrystal-metapkg files
        run: |
          set -eux
          test -f ./dist_metapkg/ncrystal-${{ needs.preparations.outputs.ncrystalversion }}.tar.gz
          test -f ./dist_metapkg/ncrystal-${{ needs.preparations.outputs.ncrystalversion }}-py3-none-any.whl

      - name: Verify presence of expected ncrystal-verify files
        run: |
          set -eux
          test -f ./dist_verify/ncrystal_verify-${{ needs.preparations.outputs.ncrystalversion }}.tar.gz
          test -f ./dist_verify/ncrystal_verify-${{ needs.preparations.outputs.ncrystalversion }}-py3-none-any.whl

      - uses: actions/upload-artifact@v4
        with:
          name: final-dist-ncrystal-core
          path: ./dist_core
          if-no-files-found: error

      - uses: actions/upload-artifact@v4
        with:
          name: final-dist-ncrystal-python
          path: ./dist_python
          if-no-files-found: error

      - uses: actions/upload-artifact@v4
        with:
          name: final-dist-ncrystal-metapkg
          path: ./dist_metapkg
          if-no-files-found: error

      - uses: actions/upload-artifact@v4
        with:
          name: final-dist-ncrystal-verify
          path: ./dist_verify
          if-no-files-found: error

  publish_to_pypi:
    name: Publish to pypi
    needs: [collect_output, basic_functionality_test]
    runs-on: ubuntu-latest
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: download ncrystal-core dist
        uses: actions/download-artifact@v4
        with:
          name: final-dist-ncrystal-core
          path: ./dist_core

      - name: download ncrystal-python dist
        uses: actions/download-artifact@v4
        with:
          name: final-dist-ncrystal-python
          path: ./dist_python

      - name: download ncrystal-metapkg dist
        uses: actions/download-artifact@v4
        with:
          name: final-dist-ncrystal-metapkg
          path: ./dist_metapkg

      - name: download ncrystal-verify dist
        uses: actions/download-artifact@v4
        with:
          name: final-dist-ncrystal-verify
          path: ./dist_verify

      - name: List files
        run: |
          find ./dist_core
          find ./dist_python
          find ./dist_metapkg
          find ./dist_verify

      - name: Combine in one dir
        run: |
          mkdir ./dist_final
          cp ./dist_core/ncrystal_core-* ./dist_final
          cp ./dist_python/ncrystal_python-* ./dist_final
          cp ./dist_metapkg/ncrystal-* ./dist_final
          cp ./dist_verify/ncrystal_verify-* ./dist_final

      - name: List files
        run: find ./dist_final

      - name: Upload distribution to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
        with:
          packages-dir: ./dist_final
          verbose: true
