name: simplebuild

on:
  push:
  pull_request:
  schedule:
    - cron: '30 18 * * 0'  # 18:30 every Sunday
jobs:
  build:

    strategy:
      matrix:
        include:
          - { os: ubuntu-latest, CC: gcc,      CXX: g++,        python: '3.13' }
          - { os: macos-latest,  CC: clang,    CXX: clang++,    python: "3.10" }

    name: ${{ matrix.os }}.${{ matrix.CC }}.python-${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.CC }}
      CXX: ${{ matrix.CXX }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}

    - name: Enable parallel cmake
      run: python ./devel/bin/ncdevtool nprocs --enable-github-parallel

    - name: pip install deps
      run: python -mpip install -r ./devel/reqs/requirements_all_and_devel.txt

    - name: simplebuild debug
      run: SIMPLEBUILD_CFG=$PWD/devel/simplebuild/cfgs/simplebuild_debug.cfg sb

    - name: simplebuild debug tests
      run: SIMPLEBUILD_CFG=$PWD/devel/simplebuild/cfgs/simplebuild_debug.cfg sb -t --testexcerpts=500 --requirepkg=NCTestAll

    - name: simplebuild reldbg
      run: SIMPLEBUILD_CFG=$PWD/devel/simplebuild/cfgs/simplebuild_reldbg.cfg sb

    - name: simplebuild reldbg tests
      run: SIMPLEBUILD_CFG=$PWD/devel/simplebuild/cfgs/simplebuild_reldbg.cfg sb -t --testexcerpts=500 --requirepkg=NCTestAll
